microsoft/vscode-java-dependency

CHANGELOG.md
jdtls.ext/com.microsoft.jdtls.ext.core/META-INF/MANIFEST.MF
jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
jdtls.ext/pom.xml
package-lock.json
package.json

Signed-off-by: andxu <andxu@microsoft.com>

update change log and bump version 0.2.0

---

jdtls.ext/com.microsoft.jdtls.ext.core/.classpath
jdtls.ext/target.target

Update project p2 dependency.

---

package-lock.json
package.json

This will downgrade event-stream from 3.3.6 to 3.3.4

Fix the vulnerability issue - update VS Code to 1.1.22

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java

Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>

Only hide the LS default project

---

src/views/documentSymbolNode.ts

Fix the bug that clicking on node will navigate the the position which contains comments

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java

Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>
Issue https://github.com/Microsoft/vscode-java-dependency/issues/125

Fix issue: Tree View will show duplicated project list for multiple root scenario

---

.gitignore
.vscode/launch.json
.vscode/tasks.json
.vscodeignore
package-lock.json
package.json
webpack.config.js

Use webpack to improve performance

Use webpack to improve performance 

---

src/java/hierarchicalPackageNodeData.ts
src/views/dataNode.ts
src/views/dependencyDataProvider.ts
src/views/dependencyExplorer.ts
src/views/fileNode.ts
src/views/hierarchicalPackageNode.ts
src/views/hierarchicalPackageRootNode.ts
src/views/nodeFactory.ts

Fix issues with hierarchical package view and typos

Fix hierarchical package view

---

package.json
package.nls.json
package.nls.zh.json

Chinese support

---

CHANGELOG.md
README.md
jdtls.ext/com.microsoft.jdtls.ext.core/META-INF/MANIFEST.MF
jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
jdtls.ext/pom.xml
package-lock.json
package.json

Add 0.5.0 release information.

---

package-lock.json
package.json
src/fileWather.ts
src/views/dependencyDataProvider.ts

Send refresh telemetry only if auto-refresh is off, and send telemetry when users switch auto-save configuration.

Send refresh telemetry only if auto-refresh is off

---

CHANGELOG.md
jdtls.ext/com.microsoft.jdtls.ext.core/META-INF/MANIFEST.MF
jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
jdtls.ext/pom.xml
package-lock.json
package.json

Bump version and add 0.5.1 release information.

Prepare for 0.5.1 release

---

src/fileWather.ts

Fix updateFileWatcher didn't invoke auto-refresh method, for issue #167.

Fix updateFileWatcher didn't invoke auto refresh method

---

jdtls.ext/com.microsoft.jdtls.ext.core/META-INF/MANIFEST.MF
jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
jdtls.ext/pom.xml
package-lock.json
package.json

Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>

bump version to 0.6.0

---

src/fileWather.ts

Add workspace folder change's watcher to sync handler

---

src/views/dependencyDataProvider.ts

Debouncer should be triggered before flushing

---

package-lock.json
package.json
src/views/dependencyExplorer.ts

Add 'CollapseAll' support in the Dependency Explorer

---

images/dark/icon-flat.svg
images/dark/icon-hierarchical.svg
images/light/icon-flat.svg
images/light/icon-hierarchical.svg

The newest tree view icon:
https://github.com/microsoft/vscode-icons/blob/master/icons/light/list-tree.svg
And the flat list view:
https://github.com/microsoft/vscode-icons/blob/master/icons/light/list-flat.svg

Use VS Code official icons for tree-list and flat-list

---

src/views/dataNode.ts

bugfix: No response when open a file with jdt uri

---

src/controllers/libraryController.ts

bugfix: Cannot remove jar if it's already in the include field

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/PackageNode.java
package.json

bugfix: Can only modify the referenced libraries in invisible project

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java

bugfix: Not show project node for non-java project

---

package-lock.json
package.json
src/views/containerNode.ts

Update to the newest codicon

---

src/controllers/projectController.ts
templates/invisible-project/README.md

Create empty lib folder when generate scaffolding

---

package.json

Add description

---

package.json
package.nls.json
package.nls.zh.json
src/views/dependencyExplorer.ts

Rename the extension to 'Project Manager for Java'

---

src/controllers/projectController.ts

bugFix: Cannot create project with no build tools

---

src/exportJarSteps/GenerateJarExecutor.ts
src/exportJarSteps/ResolveMainMethodExecutor.ts
src/exportJarSteps/ResolveWorkspaceExecutor.ts

1. Fix dependency path display in invisible projects
2. Remove useless import statements

Fix path display issue and remove useless codes

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
package.json
package.nls.json
package.nls.zh.json
src/commands.ts
src/explorerCommands/new.ts
src/java/typeRootNodeData.ts
src/utility.ts
src/views/dependencyDataProvider.ts
src/views/packageNode.ts
src/views/packageRootNode.ts

Support new class & package from explorer

---

src/views/folderNode.ts

bugfix: Cannot show folder children

---

src/views/nodeCache/explorerNodeCache.ts

bugfix: Refresh the explorer correctly when it has default package

---

src/commands.ts
src/views/dependencyDataProvider.ts

bugfix: Cannot open binary file from project explorer

---

src/controllers/projectController.ts

Better description for 'No build tools' when creating project

---

src/syncHandler.ts
src/utils/Lock.ts
src/views/dataNode.ts
src/views/dependencyDataProvider.ts
src/views/hierarchicalPackageNode.ts

bugfix: Fix the bug that the explorer will be out-of-sync occasionally

---

src/views/dependencyExplorer.ts

bugfix: Fix the NPE when focus on the output channel

---

package.json

So now we have three default groups

Set command group for 'new' actions

---

src/exportJarSteps/GenerateJarExecutor.ts

Fix Status Bar bug when exporting jar

---

src/exportJarSteps/GenerateJarExecutor.ts

Fix undefined bug when export jar

---

src/exportJarSteps/GenerateJarExecutor.ts
src/exportJarSteps/ResolveJavaProjectExecutor.ts
src/exportJarSteps/ResolveMainMethodExecutor.ts

Check if the selected item is valid when quickpick

---

src/views/folderNode.ts

fix: sort the children for folder nodes

---

src/exportJarSteps/GenerateJarExecutor.ts

Fix: Missing class files when exporting jar

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageParams.java
src/views/packageRootNode.ts

fix: Cannot show the content of a referenced jar

---

.travis.yml
extension.bundle.ts
src/extension.ts
test/gradle-suite/projectView.test.ts
test/index.ts
test/maven-suite/projectView.test.ts
test/shared.ts
test/simple-suite/projectView.test.ts

This PR fix error in current CI test process.
Test will not begin until language server is switched to the Standard mode.
Also fixed previous problem in CI (OSX will hang in build process).

chore: Fix error in CI test process

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java

fix: Cannot show Chinese project name

---

package.nls.json

refactor: Change 'Reveal in Java Projects' to 'Reveal in Java Projets Explorer'

---

package.json
src/views/dependencyExplorer.ts

fix: Prevent multiple calls of reveal() at the same time

---

src/exportJarSteps/GenerateJarExecutor.ts
src/exportJarSteps/utility.ts

When the user specifics the output file manually in export jar, the save dialog will offer a default name as the file name currently.

feat: Can show default output file name in export jar

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/PackageNode.java
src/explorerCommands/new.ts
test/shared.ts

fix: Cannot new classes/packages for unmanaged folders

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/PackageNode.java
src/exportJarSteps/GenerateJarExecutor.ts
src/exportJarSteps/ResolveJavaProjectExecutor.ts

fix: Exporting Jar lasts all time in unmanaged folders

---

package.json

ux: Add contextual title and icon for Java Project explorer

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/PackageNode.java

fix: Cannot expand for multi-module project

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageParams.java
jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/Trie.java
jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/TrieNode.java
src/views/packageRootNode.ts

fix: No context menu when explorer is in hierarchical mode

---

src/exportJarSteps/ExportJarTaskProvider.ts

fix: No pom.xml in the root path of exported jar file

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/Trie.java

fix: Cannot show compilation units under the default package

---

jdtls.ext/com.microsoft.jdtls.ext.core/.classpath
jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java

fix https://github.com/redhat-developer/vscode-java/issues/1778

fix: Cannot list multi-module projects properly

---

package-lock.json
package.json
src/views/dataNode.ts

feat: Adopt resourceUri API to the Java Project explorer

---

src/exportJarSteps/ExportJarTaskProvider.ts

fix: Save the workspace before exporting jar

---

test/gradle/.vscode/settings.json
test/maven-suite/exportJar.test.ts
test/maven/.vscode/tasks.json

test: Add unit tests for exporting jar

---

package.json

part of https://github.com/microsoft/vscode-java-pack/issues/593

adopt workspaceTrust in package.json

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
src/exportJarSteps/GenerateJarExecutor.ts
src/java/jdtls.ts

fix: "Cancel" of generating jar takes no effect

---

package.json

Follow lastest API in https://github.com/microsoft/vscode-java-dependency/issues/489

disable untrustedWorkspaces support

---

src/exportJarSteps/utility.ts

chore: Remove "done" from the message of export jar

---

src/exportJarSteps/ExportJarTaskProvider.ts

fix: Export jar reports have wrong format in macOS

---

src/exportJarSteps/ExportJarTaskProvider.ts

fix #516 
reference: https://github.com/microsoft/vscode/issues/125725#issuecomment-856597312

fix: Export jar task finishes with error

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java

fix: Exceptions when opening a file which is not on the build path

---

src/extension.ts

fix #532 
We should not activated JLS manually. Instead, polling it to check if it has been activated

fix: Do not activate the Java Language Server

---

src/explorerCommands/new.ts

fix: Create untitled new file when JLS is not ready

---

package-lock.json
package.json
src/views/containerNode.ts

ui: Adopt new folder-library icon

---

package.json

Fix #568 type error

---

CHANGELOG.md
jdtls.ext/com.microsoft.jdtls.ext.activator/META-INF/MANIFEST.MF
jdtls.ext/com.microsoft.jdtls.ext.activator/pom.xml
jdtls.ext/com.microsoft.jdtls.ext.core/META-INF/MANIFEST.MF
jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
jdtls.ext/pom.xml
package-lock.json
package.json

chore: Prepare for 0.18.9

---

jdtls.ext/target.target

chore: Remove log4j in target platform definition

---

src/controllers/projectController.ts

Now the list looks like following:

feat: Support creating new Gradle project

---

templates/invisible-project/.vscode/settings.json

fix: Add default setting for referenced libraries

---

CHANGELOG.md
jdtls.ext/com.microsoft.jdtls.ext.activator/META-INF/MANIFEST.MF
jdtls.ext/com.microsoft.jdtls.ext.activator/pom.xml
jdtls.ext/com.microsoft.jdtls.ext.core/META-INF/MANIFEST.MF
jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
jdtls.ext/pom.xml
package-lock.json
package.json

chore: Prepare for 0.19.0

---

src/controllers/projectController.ts

fix: Record the selected project type

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ExtUtils.java
package-lock.json
package.json

fix: Add null check

---

test/java9/pom.xml

chore: Update gson in test projects

---

.github/workflows/linux.yml
.github/workflows/linuxUI.yml
.github/workflows/macOS.yml
.github/workflows/windows.yml
.github/workflows/windowsUI.yml
jdtls.ext/pom.xml
test/gradle/.vscode/settings.json

chore: Update to JDK 17 in CIs

---

src/extension.ts
src/languageServerApi/languageServerApiManager.ts
src/syncHandler.ts

fix: Adopt serverReady() API

---

src/commands.ts
src/extension.ts
src/languageServerApi/languageServerApiManager.ts
src/settings.ts
src/syncHandler.ts
src/views/dependencyDataProvider.ts
src/views/explorerNode.ts

fix: Lose refresh events when debounce

---

src/views/DragAndDropController.ts

part of #613 
This PR adds a overwrite confirmation when the target file already exists in the file system.

fix: Add overwrite confirmation

---

src/controllers/libraryController.ts
src/views/DragAndDropController.ts

part of #613. 
Drag folders from the VS Code's file explorer to the referenced libraries node is not supported due to an issue: https://github.com/microsoft/vscode/issues/152031

feat: Support adding referenced libraries via drag and drop

---

src/views/DragAndDropController.ts

feat: Support copy files from file explorer

---

src/views/DragAndDropController.ts

bi: Add telemetry for dnd support

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
src/views/hierarchicalPackageNode.ts
src/views/packageNode.ts

fix: Show folders in the package nodes

---

CHANGELOG.md
jdtls.ext/com.microsoft.jdtls.ext.activator/META-INF/MANIFEST.MF
jdtls.ext/com.microsoft.jdtls.ext.activator/pom.xml
jdtls.ext/com.microsoft.jdtls.ext.core/META-INF/MANIFEST.MF
jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
jdtls.ext/pom.xml
package-lock.json
package.json

chore: Prepare for 0.20.0

---

package-lock.json
package.json

chore(deps): Bump vscode-extension-telemetry-wrapper to 0.13.1

---

package-lock.json
package.json
src/views/DragAndDropController.ts

fix: Cannot drag from VS Code's file explorer to Java Project explorer

---

package-lock.json
package.json
src/exportJarSteps/ExportJarTaskProvider.ts
src/exportJarSteps/GenerateJarExecutor.ts

it's a follow-up of https://github.com/microsoft/vscode-java-dependency/pull/592#issuecomment-1035902532

chore: Update `globby` and `copy-webpack-plugin`

---

CHANGELOG.md
jdtls.ext/com.microsoft.jdtls.ext.activator/META-INF/MANIFEST.MF
jdtls.ext/com.microsoft.jdtls.ext.activator/pom.xml
jdtls.ext/com.microsoft.jdtls.ext.core/META-INF/MANIFEST.MF
jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
jdtls.ext/pom.xml
package-lock.json
package.json

chore: Prepare for 0.21.0

---

package.json

fix: Scan two levels of directories for activation indicators

---

src/explorerCommands/new.ts
src/views/packageRootNode.ts

fix: Do not allow craeting new types in resource folder

---

src/tasks/buildArtifact/GenerateJarExecutor.ts
src/tasks/buildArtifact/utility.ts

fix #676 , also remove ExportJarTargets since it's not used any more.

chore: remove ASKUSER option

---

package-lock.json
package.json
test/ui/command.test.ts

chore(deps): Update dependencies

---

package-lock.json
package.json
tsconfig.json

chore: Bump dependency versions

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java

- When comparing the project location with the workspace folder path, scan the folder with one level deep and check if the linked folder belongs to the workspace folder.
fix #691 

fix: Better handling the linked resource when getting projects

---

src/tasks/buildArtifact/BuildArtifactTaskProvider.ts

fix: Add eol after emitting export jar end message

---

.github/workflows/linux.yml
.github/workflows/macOS.yml
.github/workflows/windows.yml
package-lock.json
package.json

- To match the requirement of the dependency @vscode/test-electron@2.2.2

Update the CI node version

---

README.md

chore: Update the badges

---

CHANGELOG.md
src/views/dataNode.ts
test/maven-suite/projectView.test.ts

feat: Apply file decorators to project level

---

package.json
package.nls.json
package.nls.zh-cn.json
package.nls.zh-tw.json
src/commands.ts
src/explorerCommands/new.ts
src/views/dependencyExplorer.ts

feat: Support create different kind of resources from inline new button.

---

package.json
src/views/projectNode.ts
test/suite/contextValue.test.ts

fix https://github.com/microsoft/vscode-gradle/issues/1396

feat: Support showing Gradle sub-menu for BSP Gradle projects

---

.azure-pipelines/ci.yml
.azure-pipelines/nightly.yml
.azure-pipelines/rc.yml
.github/workflows/linux.yml
.github/workflows/linuxUI.yml
.github/workflows/macOS.yml
.github/workflows/windows.yml
.github/workflows/windowsUI.yml
jdtls.ext/com.microsoft.jdtls.ext.target/com.microsoft.jdtls.ext.tp.target
package-lock.json
package.json
test/index.ts

- Update nodejs to 20.x
- Update lsp4j tp 0.23.1

build - Update dependencies

---

jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java

Improve ProjectCommand.getMainClasses
