- src/views/dependencyExplorer.ts
fix error when window.activeTextEditor is undefined
> fix error when window.activeTextEditor is undefined

- src/views/dependencyDataProvider.ts
Fix #176 
Local variable is used to avoid concurrent modification, so when `this._rootItems` is set to null asynchronously, the execution of `getRootNodes` will not be affected.
> Fix Uncaught exception is throw in VS Code Developer Tools

- src/controllers/projectController.ts
- src/utility.ts
> Replace workspace.rootPath with workspaceFolder

- images/dark/icon-flat.svg
- images/dark/icon-hierarchical.svg
- images/dark/icon-link.svg
- images/dark/icon-refresh.svg
- images/dark/icon-unlink.svg
- images/light/icon-flat.svg
- images/light/icon-hierarchical.svg
- images/light/icon-link.svg
- images/light/icon-refresh.svg
- images/light/icon-unlink.svg
Resolve: https://github.com/microsoft/vscode-java-dependency/issues/197
One problem is that in the light theme, the color defined in the [VSCode-Icons] repo is not aligned within the VS Code. So it would be really helpful if VS Code can expose the API to let the extension reuse its icons. See: https://github.com/microsoft/vscode/issues/31466
> Update explorer icons using vscode-icons

- src/views/containerNode.ts
- src/views/dataNode.ts
- src/views/packageRootNode.ts
This PR adds support of view nodes' context value.
It is the base of PR #208, #213.
> Support context value of view nodes

- src/settings.ts
- src/views/dependencyDataProvider.ts
This PR
* Refactor the `onDidChangeConfiguration` hanlder in favor of`listener(updatedConfig, oldConfig)` pattern.
* move the old logic into separate listeners
* makes sure that when a listener gets called, it will receive the **latest** configuration from `Settings.getSomeSetting`.
> Refactor onDidChangeConfiguration handler in favor of listener pattern

- src/java/hierarchicalPackageNodeData.ts
- src/views/dataNode.ts
- src/views/hierarchicalPackageNode.ts
- src/views/packageRootNode.ts
> Support showing file path as description for external jar files

- images/dark/icon-add.svg
- images/dark/icon-remove.svg
- images/light/icon-add.svg
- images/light/icon-remove.svg
- jdtls.ext/com.microsoft.jdtls.ext.core/plugin.xml
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/CommandHandler.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/JdtlsExtActivator.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
- package-lock.json
- package.json
- package.nls.json
- package.nls.zh.json
- src/commands.ts
- src/controllers/libraryController.ts
- src/controllers/projectController.ts
- src/extension.ts
- src/java/jdtls.ts
- src/settings.ts
- webpack.config.js
Fix #174, https://github.com/microsoft/vscode-java-pack/issues/94 
Based on:
VS Code will take care of the file watching and searching work by providng a setting:
```typescript
"java.dependency.referencedLibraries": string[] | {
"include": string[],
"exclude": string[],
"sources": { [binary: string]: string }
}
```
...with the following extended behaviors before sending to `jdt.ls`:
* If specified setting is an array, it will be expanded into a full object, with the original content as `include` field. 
* Jars in `lib/` but not `included` will be appended to `exclude` field. It is to ensure jars not listened by VS Code don't get shown in referenced libraries — only one source of truth. (This is not an elegent workaround, waiting for better alternative...)
* A match of `foo.jar` and …
> Support managing referenced libraries

- package.json
- package.nls.json
- package.nls.zh.json
- src/commands.ts
- src/controllers/libraryController.ts
- src/views/containerNode.ts
Register a command into the `Maven Dependencies` node and it will call the real command provided by `VS Code Maven`
> faet: Add dependency to Maven projects

- src/views/dependencyExplorer.ts
fix #231
1. check `this._dependencyViewer.visible` in `window.onDidChangeActiveTextEditor` to avoid redundant invocation of `java.getPackageData`
2. Put disposables into subscriptions
3. Directly call `reveal` when the visibility of the explorer changed. No need to cache `_selectionWhenHidden` anymore
> bugfix: Stop calling 'java.getPackageData' when the dependency explorer is not visible

- package.json
- package.nls.json
- package.nls.zh.json
- src/controllers/projectController.ts
> Add more project types for creation and expose the command in explorer

- .travis.yml
VS Code Java requires JDK 11 to launch now.
> Use JDK 11 on travis

- src/exportJarSteps/GenerateJarExecutor.ts
- src/exportJarSteps/ResolveMainMethodExecutor.ts
- src/exportJarSteps/utility.ts
when no main method, set mainMethod to an empry string instead of using basename(string).
> Fix bug when no main method

- src/explorerCommands/new.ts
fix #304 
Create package from a default package should have the same behavior as creating from package root
> bugfix: Wrong package created under the default package

- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/PackageNode.java
- src/java/nodeData.ts
- src/views/dataNode.ts
> Use folder name as the name of the invisible project

- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/PackageNode.java
- package.json
- package.nls.json
- package.nls.zh.json
- src/commands.ts
- src/constants.ts
- src/controllers/libraryController.ts
- src/extension.ts
- src/java/nodeData.ts
- src/views/containerNode.ts
- src/views/dataNode.ts
- src/views/packageNode.ts
- src/views/packageRootNode.ts
- src/views/projectNode.ts
- src/views/workspaceNode.ts
- test/explorer/contextValue.test.ts
This PR is to better expose the node context value.
`java:<node type>[+<attribute>]*`
Currently, available node types are:
- `workspaceFolder`
- `project`
- `container`
- `packageRoot`
- `package`
- `jar`
Not available node types are:
- `folder`
- `file`
- `type` (class, enum, interface,...)
Below picture illustrates the different node types
For each node type, it may have some attributes. Every attribute will start with a `+`.
- `+uri`: The node has uri
**Project Node**:
- `+java`: Java project
- `+maven`: Maven project
- `+gradle`: Gradle project
**Container Node**:
- `+jre`: Container for JRE
- `+maven`: Container for Maven
- `+gradle`: Container for Gradle
- `+referencedLibrary`: Container for Referenced Libraries
**Package Root Node**:
- `+source`: Source package root.
- `+resource`: …
> Refine the context value of the nodes in the project explorer

- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageParams.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/PackageNode.java
- src/syncHandler.ts
- src/views/dependencyDataProvider.ts
- src/views/folderNode.ts
- src/views/packageNode.ts
- src/views/packageRootNode.ts
- src/views/projectNode.ts
Before:
After:
--- Updated---
When root has content
When root is empty
> Do not display workspace link '_' for invisible project

- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/PackageNode.java
- src/constants.ts
- src/explorerCommands/new.ts
- src/views/nodeCache/explorerNodeCache.ts
Source with default package:
Binary with default package: (e.g. default package that stores the module-info.class)
fix #313
> Directly show children under default package

- src/exportJarFileCommand.ts
- src/exportJarSteps/GenerateJarExecutor.ts
- src/exportJarSteps/IExportJarStepExecutor.ts
- src/exportJarSteps/IStepMetadata.ts
- src/exportJarSteps/ResolveJavaProjectExecutor.ts
- src/exportJarSteps/ResolveMainMethodExecutor.ts
- src/exportJarSteps/utility.ts
Use an array to record the steps to fix the backbutton issue.
Also move `IStepMetadata` to a single file and do a small refactor in `IJarQuickPickItem` to avoid any misunderstanding.
> Fix backbutton issue

- package.json
- src/explorerCommands/new.ts
Add the `create new class` action as an inline button for `project`, `packageRoot` & `package` nodes
> feat: Add inline button for create new class

- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
- package-lock.json
- package.json
- src/constants.ts
- src/extension.ts
- src/views/dataNode.ts
- src/views/dependencyDataProvider.ts
- src/views/dependencyExplorer.ts
> feat: Add 'Reveal in Java Projects' in editor titile context

- package.json
`never` will not work if someone set it as a context value
> chore: Change 'never' to 'false' in when clause

- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
- package-lock.json
- package.json
- package.nls.json
- package.nls.zh.json
- src/exportJarFileCommand.ts
- src/exportJarSteps/ExportJarTaskProvider.ts
- src/exportJarSteps/GenerateJarExecutor.ts
- src/exportJarSteps/IStepMetadata.ts
- src/exportJarSteps/ResolveJavaProjectExecutor.ts
- src/exportJarSteps/ResolveMainMethodExecutor.ts
- src/exportJarSteps/utility.ts
- src/java/jdtls.ts
- src/settings.ts
- src/views/dependencyDataProvider.ts
fix #330 
This PR includes following things:
1. Use `vscode.task` to refactor export process to make it is possible to parse VS Code variables like `${workspaceFolder}`.
2. Offer a setting named `defaultTargetFolder`, which can change the default target path of export jar by opening a dialog.
3. Some enhancement in `jdtls.ext`, such as error reporting and variables renaming
4. Some changes in `IStepMetadata` to make it sense.
> Specific target folder when exporting jar and enhancement of jdtls.ext

- test/explorer/contextValue.test.ts
Since we have added `File/Type` in `ContextValueType`, it's necessary to add test cases for them.
Tested context value in this PR:
- `java:file+uri`
- `java:type+class+uri`
- `java:type+enum+uri`
- `java:type+interface+uri`
> test: Add test cases for new context value

- package.json
- src/constants.ts
- src/explorerCommands/utils.ts
- src/views/folderNode.ts
- test/explorer/contextValue.test.ts
- Add new type `Folder` into `ContextValueType`
- Also enabled context menu for non-package folder and resource packageRoot
- Test case for new context value
> feat: Add context value for folder

- src/explorerCommands/new.ts
- src/explorerCommands/rename.ts
- src/explorerCommands/utils.ts
This PR fixed two parts:
1. Input validation:
- If user rename `PrimaryTypeNode`, then:
1) Input should be a legal Java identifier 
- If user rename `packageRoot` or `packageRootNode`, then:
1) Input should also be a legal identifier
3) Could not contain `.`, due to limitations, currently we can only rename innermost package
2. Pre-fill value:
- For package, since cross-level rename is not supported, we only show innermost folder name
- For `PrimaryTypeNode`, only show class name
- For other files, show extension name, but not pre-selected
> fix: Validate input & change pre-fill value

- package.json
- src/explorerCommands/delete.ts
- src/explorerCommands/rename.ts
- src/explorerCommands/utility.ts
- src/views/dependencyDataProvider.ts
- src/views/dependencyExplorer.ts
Add keybindings for `Reveal in Explorer`, `Copy Path`, `Copy Relative Path`.
> feat: Add more keybindings for context menu

- extension.bundle.ts
- gulpfile.js
- package.json
- package.nls.json
- package.nls.zh.json
- src/commands.ts
- src/controllers/projectController.ts
- src/exportJarSteps/ExportJarTaskProvider.ts
- src/extension.ts
- src/languageServerApi/LanguageServerMode.ts
- src/languageServerApi/languageServerApiManager.ts
- src/views/dataNode.ts
- src/views/dependencyDataProvider.ts
- src/views/dependencyExplorer.ts
- src/views/hierarchicalPackageNode.ts
- test/shared.ts
> fix: Do not display Java Project explorer in non-Java workspace

- src/exportJarSteps/ExportJarTaskProvider.ts
- src/exportJarSteps/GenerateJarExecutor.ts
- src/exportJarSteps/IExportJarStepExecutor.ts
- src/exportJarSteps/IStepMetadata.ts
- src/exportJarSteps/ResolveJavaProjectExecutor.ts
- src/exportJarSteps/ResolveMainClassExecutor.ts
- src/exportJarSteps/utility.ts
Fix #385 
This PR fixs:
1. Enables null check and implicit any for export jar files
2. Refactor error reporting and telemetry sending in export jar.
> refactor: Error reporting and null check in export jar

- src/views/hierarchicalPackageNode.ts
Since the modular JDK has the same `jrtfs` path. So we need to take its name into consideration as well
> fix: Cannot show JDK class node in hierarchical mode

- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
- src/utility.ts
- src/views/dataNode.ts
- src/views/dependencyDataProvider.ts
- src/views/dependencyExplorer.ts
When we open a non-java file which doesn't belong to the opened project, LS will throw NPE error, since in `resolvePath` api we assume the file should be in workspace. So, additional checks are needed.
fix #418
> fix: NPE error when open non-project file

- package-lock.json
- package.json
- src/commands.ts
- src/extension.ts
- src/utility.ts
- src/views/PrimaryTypeNode.ts
- src/views/dependencyDataProvider.ts
- src/views/dependencyExplorer.ts
- src/views/fileNode.ts
- src/views/symbolNode.ts
This PR changes two parts:
1. From VS Code 1.52, all custom tree behavior has been changed, which enable our plugin to have more consistent experience with file explorer when open file. That means, all following interactions are enabled for `fileNode` and `primaryTypeNode`:
- Double-click or mouse-middle-click to open in non-preview.
- Enter to open in non-preview mode (Space to open in preview mode).
- Alt+Click to open an editor to the side of the active one.
reference: [https://code.visualstudio.com/updates/v1_52](ref)
2. Since changes above needs to register `vscode.open` as TreeItem's command id, we can not use customized `java.view.package.openFile` command to send telemetry. As compensate, we send these additional info in telemetry:
- `{projectManagerVisible: 1}` when project …
> feat: Make openFile experience consistent with built-in trees

- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
> fix: Export Jar wizard shows main classes from libraries

- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
- src/utility.ts
- src/views/PrimaryTypeNode.ts
- src/views/hierarchicalPackageNode.ts
- src/views/hierarchicalPackageRootNode.ts
- src/views/packageNode.ts
- src/views/packageRootNode.ts
- src/views/projectNode.ts
- test/suite/contextValue.test.ts
- tslint.json
This PR add `+test` attributes to the test nodes.
If a package fragment root has following attributes, then it is marked as a test root:
- `test=true`
- `maven.scope` includes `test`
- `gradle_scope` includes `test`
When a package fragment root is a test root, then itself and all of its children will have a test attribute `+test`.
> feat: Add test metadata to the nodes

- package.json
fix #436 
This PR sorts all available commands contributed by Java Project Manager in the command palette into two kinds.
1. The command which can execute independently from the project view. It will trigger the activation of `Java Project Manager` first.
- `java.view.package.exportJar`
2. The commands which are related with the project view. Since the users would most trigger them from the project view and the existence of them in the command palette may cause ambiguity, we hide them in the command palette.
- `java.view.package.refresh`
- `java.view.package.changeToHierarchicalPackageView`
- `java.view.package.changeToFlatPackageView`
- `java.view.package.linkWithFolderExplorer`
- `java.view.package.unlinkWithFolderExplorer`
Also, a change in the when clause of the **inline** `Export …
> fix: Command 'Java: Export Jar...' resulted in an error

- package.json
- package.nls.json
- package.nls.zh.json
- src/commands.ts
- src/controllers/libraryController.ts
Fixes #238
When trying to add a library to `Referenced Libraries` for invisible projects on Linux, all files are grayed out (unselectable), and you can't even navigate into folders. This makes it impossible to add libraries for invisible projects on Linux, unless you modify the settings.json manually.
This is caused by the unclear API docs for [OpenDialogOptions](https://code.visualstudio.com/api/references/vscode-api#OpenDialogOptions), which say:
> A dialog can select files, folders, or both. This is not true for Windows which enforces to open either files or folder, but *not both*.
This extension then assumes that `canSelectFiles` and `canSelectFolders` can be activated at the same time on both macOS and Linux - but it's actually unsupported on both Windows *and Linux* (which is the …
> Fix add libraries dialog not working on Linux

- CHANGELOG.md
as @0dinD [mentioned](https://github.com/microsoft/vscode-java-dependency/pull/441#issuecomment-758640870), offer alternative key `shift` + click in CHANGELOG.md because `alt` + click is reserved by default in Linux.
> fix: Modify CHANGELOG.md for Linux users when adding library folders

- src/utility.ts
- src/views/dependencyExplorer.ts
> fix: Cannot reveal the explorer when 'java.dependency.syncWithFolderExplorer' is off

- package.json
- package.nls.json
- package.nls.zh.json
- src/constants.ts
- src/views/dependencyDataProvider.ts
Address https://github.com/microsoft/vscode-java-pack/issues/540
> fix: Show welcome view when no Java projects in workspace

- src/build.ts
This PR is a workaround to #459, continue to keep eyes on further discussions in https://github.com/microsoft/vscode/issues/116932.
> fix: export jar doesn't report error when grammatical error exists 

- package-lock.json
- package.json
- src/languageServerApi/languageServerApiManager.ts
- src/utility.ts
- src/utils/Lock.ts
- src/views/dataNode.ts
- src/views/dependencyDataProvider.ts
- src/views/dependencyExplorer.ts
- src/views/hierarchicalPackageNode.ts
> bugfix: Data tree node not found

- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
- src/commands.ts
- src/exportJarSteps/ExportJarTaskProvider.ts
- src/exportJarSteps/GenerateJarExecutor.ts
- src/exportJarSteps/IStepMetadata.ts
- src/exportJarSteps/utility.ts
- src/java/jdtls.ts
- src/views/dependencyDataProvider.ts
> feat: Report messages when exporting jar

- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
- src/exportJarSteps/ExportJarTaskProvider.ts
- src/exportJarSteps/GenerateJarExecutor.ts
- src/exportJarSteps/IStepMetadata.ts
- src/exportJarSteps/ResolveMainClassExecutor.ts
- src/exportJarSteps/utility.ts
- src/java/jdtls.ts
- src/views/dependencyDataProvider.ts
fix #506 
This PR includes two things:
- Use `terminalId`, which is a random number, instead of `taskLabel` to indicate the execution terminal in case of two terminals with the same name.
- Close the execution terminal once it receives a ending report.
> fix: Close terminal after receiving messages completely

- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
fix #507 
The issue about logging after cancelling has been addressed in #510. This PR removes the corrupted jar after cancellation.
> fix: Misleading behavior after cancelling exporting jar

- package-lock.json
- package.json
- src/commands.ts
- src/explorerCommands/new.ts
- src/views/dependencyExplorer.ts
1. If there is a active text editor and it's uri belongs to a workspace folder, then generate a new class at the same folder
2. Otherwise, ask user to select target project (if multiple) and package
3. If no project is opened, ask user to create a new project
resolve https://github.com/microsoft/vscode-java-pack/issues/706
> feat: Support new file contribution

- package.json
- package.nls.json
- package.nls.zh.json
- src/constants.ts
- src/exportJarSteps/ExportJarTaskProvider.ts
- src/extension.ts
- src/languageServerApi/languageServerApiManager.ts
- src/utility.ts
- src/views/dependencyDataProvider.ts
- src/views/dependencyExplorer.ts
The PR is to let the Java Project explorer properly show hints for users:
- When `redhat.java` is not installed, hint for installation
- When no Java projects found, hint for creation/opening
- When JDT.LS in Lightweight mdoe, hint for switching.
Now the activation events is the same as `redhat.java`. But since events like `workspaceContains` is not supported in when clause, so I use APIs to query files during activation and set context value to imitate the condition:
- `resourceLangId == java` is for `onLanguage:java`
- `java:workspaceContainsBuildFiles` -> `workspaceContains`
- `java:serverMode` is to make sure the explorer will always visible once JDT.LS is activated. (still visible when user switch focus to a non-Java file)
> fix: Show the hints in Java Projects explorer properly

- .github/workflows/linux.yml
- .github/workflows/linuxUI.yml
- .github/workflows/macOS.yml
- .github/workflows/windows.yml
- .github/workflows/windowsUI.yml
Since the newest vsce (2.5.1) requires at least node 14 to run, the current pipelines are broken.
> chore: Upgrade to node 14 in GitHub pipelines

- package-lock.json
- package.json
- src/controllers/projectController.ts
- test/ui/command.test.ts
part of https://github.com/microsoft/vscode-java-pack/issues/856
> feat: Support create JavaFX projects

- package.json
- package.nls.json
- package.nls.zh.json
- src/commands.ts
- src/explorerCommands/delete.ts
- src/views/dependencyExplorer.ts
fix #608
Since some platform may not contain recycle bin. So we have to check the context key `explorerResourceMoveableToTrash` to make sure the capability is available. The new command `java.view.package.deleteFilePermanentely` is added and be used when recycle bin is not available.
> fix: Remove file from remote environment

- src/views/dependencyExplorer.ts
fix #588 
See :https://github.com/microsoft/vscode-java-dependency/issues/588#issuecomment-1150581321 for how to repro this bug in the marketplace version
> fix: Duplicated tree items show in the explorer

- src/views/DragAndDropController.ts
- src/views/containerNode.ts
- src/views/explorerNode.ts
- src/views/packageRootNode.ts
- src/views/projectNode.ts
> feat: Support drag and drop inside Java Project explorer

- src/constants.ts
- src/views/DragAndDropController.ts
- src/views/documentSymbolNode.ts
- src/views/explorerNode.ts
- src/views/packageNode.ts
- src/views/symbolNode.ts
> fix: Use context value to identify the node types

- src/views/DragAndDropController.ts
fix https://github.com/microsoft/vscode-java-dependency/issues/613#issuecomment-1168162227
> fix: Document symbol should not be dropped to Project explorer

- src/views/DragAndDropController.ts
In flat view, a package should not be able to move to its parent package.
> fix: Check file path as well when moving

- package.json
- package.nls.json
- package.nls.zh-cn.json
- package.nls.zh-tw.json
- src/commands.ts
- src/constants.ts
- src/extension.ts
- test/maven-suite/context.test.ts
> feat: Show reload button at editor title when there is reload required diagnostics

- package.json
- src/commands.ts
- src/constants.ts
- src/exportJarSteps/ExportJarTaskProvider.ts
- src/extension.ts
- src/tasks/migration/CodeActionProvider.ts
- src/tasks/migration/DiagnosticProvider.ts
- src/tasks/migration/utils.ts
- test/maven-suite/exportJar.test.ts
- test/maven/.vscode/tasks.json
fix #665 
This pr also renames the default label from `java: exportjar:${workspaceName}` to `java (buildArtifact): ${workspaceName}`. We can still find `java` type via `Run Tasks...`, but the provider will not provide any template tasks anymore. If there is no `java` tasks in your tasks.json, the result of clicking `java` type will be empty.
> UX: Change export task type to `java (buildArtifact)`

- extension.bundle.ts
- src/languageServerApi/languageServerApiManager.ts
- src/tasks/buildArtifact/BuildArtifactTaskProvider.ts
- test/maven-suite/buildArtifact.test.ts
fix #720 
This PR contains two things:
- catch potential exceptions when sending request to jdtls
- wait 1s at most when getting the language server status. Once timeout, will directly return original task (when resolving tasks) or undefined (when providing tasks)
> fix: Make export jar task unblock fetch task process

- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/NodeKind.java
- package.json
- src/java/nodeData.ts
- src/views/containerNode.ts
- src/views/dataNode.ts
- src/views/folderNode.ts
- src/views/hierarchicalPackageNode.ts
- src/views/hierarchicalPackageRootNode.ts
- src/views/nodeFactory.ts
- src/views/packageNode.ts
- src/views/packageRootNode.ts
- src/views/projectNode.ts
- src/views/workspaceNode.ts
- Use factory pattern to create nodes. This can remove a lot of duplicated codes.
- Redefine the `NodeKind` enum to better sort the nodes in explorer
> refactor: Use factory pattern to create explorer nodes

- CHANGELOG.md
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/parser/ResourceSet.java
- src/explorerCommands/rename.ts
- src/syncHandler.ts
- src/views/projectNode.ts
- test/gradle-suite/projectView.test.ts
- test/maven-suite/projectView.test.ts
- test/simple-suite/projectView.test.ts
Fix #145 
The new explorer will looks like this:
> feat: Display non-java resources in the Project explorer

- CHANGELOG.md
- src/java/jdtls.ts
- src/settings.ts
- test/maven-suite/projectView.test.ts
- test/maven/.vscode/settings.json
fix #214 
gif:
---
Different from #216, in this PR, the logic is controlled at client side, since this is a client related setting. Using `org.eclipse.core.resources.regexFilterMatcher` will modify the `.project` file which is not ideal - mess user's SCM.
> fix: Apply 'files.exclude' to Java Projects explorer

- CHANGELOG.md
- package.json
- package.nls.json
- package.nls.zh-cn.json
- package.nls.zh-tw.json
- src/commands.ts
- src/explorerCommands/new.ts
- src/views/PrimaryTypeNode.ts
- src/views/dependencyExplorer.ts
- test/suite/contextValue.test.ts
> feat: Support creating new files/folders in Java Project explorer

- CHANGELOG.md
- extension.bundle.ts
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
- src/java/jdtls.ts
- test/maven-suite/projectView.test.ts
> feat: Show non Java Projects in the Java Projects explorer

- CHANGELOG.md
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/parser/JavaResourceVisitor.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/parser/ResourceSet.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/parser/ResourceVisitor.java
- test/maven-suite/projectView.test.ts
- test/maven/pom.xml
- test/maven/src/main/java/module-info.java
> fix: Show 'module-info.java' at source roots

- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
- src/views/dependencyDataProvider.ts
Since we will now display non Java projects (#744), the logic to check import error(#740) needs to be changed.
Now before we try to get the project nodes, we will first check if there is potential import errors. The extension will consider there is an import error if:
- No Java Project is imported into workspace except for default project
- There is at least one error marker in workspace.
> fix: Better handling the import error hint

- package-lock.json
- package.json
Since we are now using new when clause gramma, update the required VS Code version to 1.77.0 to avoid unexpected feature failure.
https://github.com/microsoft/vscode/issues/175540#issuecomment-1494256462
> chore: Update VS Code engine version to 1.77.0

- package.nls.json
fixed a misspelling for the workbench.noJavaProject snippet
> fix: spelling mistake in workbench Java Projects

- src/controllers/projectController.ts
Adding support for creating Graal Cloud Native (GCN) projects. GCN projects can be created by calling the 'gcn.createGcnProject' command provided by the [Graal Cloud Native Tools](https://marketplace.visualstudio.com/items?itemName=oracle-labs-graalvm.gcn) extension. For more information on GCN, see [https://www.graal.cloud](https://www.graal.cloud).
> feat: Support create Graal Cloud Native projects.

- src/controllers/projectController.ts
Modified to follow recent change of the extension names on the Marketplace. See https://marketplace.visualstudio.com/items?itemName=oracle-labs-graalvm.micronaut and https://marketplace.visualstudio.com/items?itemName=oracle-labs-graalvm.gcn
> Modified to follow changed extension names.

- jdtls.ext/com.microsoft.jdtls.ext.target/com.microsoft.jdtls.ext.tp.target
- package-lock.json
- package.json
- package.nls.json
- package.nls.zh-cn.json
- package.nls.zh-tw.json
- src/commands.ts
- src/controllers/projectController.ts
- test/ui/command.test.ts
- Record the UI entry that triggers the "new java project" command.
- Contribute "New Java Project..." command to the top "**File -> New File...**" menus.
- Contribute "New Java Project..." command to the context menu of File Explorer.
> Contribute 'New Java Project...' command to File/NewFile and File Explorer menus

- .github/workflows/linuxUI.yml
- .github/workflows/windowsUI.yml
- .vscode/launch.json
- README.md
- package-lock.json
- package.json
- test/ui/command.test.ts
See https://github.com/microsoft/vscode-java-dependency/actions/runs/7418895445/job/20187526152, the UI test doesn't run in the windows-UI CI job (`0 passing`). Updating the library vscode-extension-tester to the latest version 7.0.0 (which requires a minimum vscode@1.83.1) can fix it.
> Update vscode-extension-tester to 7.0.0 & minimum vscode version to 1.83.1

- .azure-pipelines/nightly.yml
- .azure-pipelines/rc.yml
- package.json
- src/explorerCommands/new.ts
- src/views/dependencyExplorer.ts
- Add 'New Java File' menu to file explorer
- Put the existing menus such as 'Reveal in Java Project Explorer', 'New Java Project...' into the same category as other Java context menus.
> Add 'New Java File' menu to file explorer & adjust the existing file explorer menu order

- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/model/PackageNode.java
- src/views/containerNode.ts
- src/views/packageRootNode.ts
- test/suite/contextValue.test.ts
The referenced libraries should only be editable for unmanaged folders in the explorer.
> fix: Referenced Libraries container should be immutable for build tool projects

- src/syncHandler.ts
- src/views/dependencyDataProvider.ts
> Fix #828: creates file watcher with trailing slash causes problems for other extensions

- src/controllers/projectController.ts
`Micronaut® Launch` extension recently renamed to `Launch for Micronaut® framework`.
> Micronaut® Launch extension renamed.

- src/controllers/projectController.ts
The `Graal Cloud Native Launcher` extension has been recently renamed to `Graal Development Kit for Micronaut Launcher`
> Graal Cloud Native Launcher extension renamed.

- jdtls.ext/com.microsoft.jdtls.ext.core/plugin.xml
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/CommandHandler.java
- jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java
- package-lock.json
- package.json
Testing against some popular java repo 
[jbang](https://github.com/jbangdev/jbang)
[Mixin](https://github.com/SpongePowered/Mixin)
[Velocity](https://github.com/PaperMC/Velocity)
java deps cost - execute java command time cost
pack cost - execute context provider to collect and return context whole time cost
|file url|java-deps cost|pack cost|
|--|--|--|
|[Configuration.java](https://github.com/jbangdev/jbang/blob/main/src/main/java/dev/jbang/Configuration.java)|9.82 ms|13 ms 7 items|
|[PathTypeAdapter.java](https://github.com/jbangdev/jbang/blob/main/src/main/java/dev/jbang/util/PathTypeAdapter.java)|4.36ms |15ms 0 items|
|[VersionChecker.java](https://github.com/jbangdev/jbang/blob/main/src/main/java/dev/jbang/util/VersionChecker.java)|4.6ms|13ms 3 items| …
> feat: add getImportClassContent method to collect import class info
